--MEDR_GUARANTEES
select
    PROJECT_NAME,
    PROJECT_DES,
    BANK_NAME,
    GUARANTEE_TYPE_DES,
    BANK_GUARANTEE_REFERENCE,
    ACC_DES,
    GUARANTEE_AMOUNT,
    REVALUED_GUARANTEE_AMOUNT,
    GUARANTEE_START_DATE,
    GUARANTEE_END_DATE,
    GUARANTEED_ENTITY_NAME,
    SOURCE_DB
from {{ ref('GUARANTEES_STG') }}