select
    "PERIOD" as BUD_CONTROL_PERIOD_ID,
    DOC      as PROJECT_ID,
    DOCNO    as PROJECT_NAME,
    CONMONTH as BUD_CONTROL_MONTH,
    CONDATE  as BUD_CONTROL_DATE,
    CURVERSION,
    SOURCE_DB
from {{ ref('BUD_CONTROLPERIODS_Z_J') }}