select
    PROJACT    as PROJPLAN_ID,
	DOC        as PROJECT_ID,
	"VERSION"  as VERSION_ID,
	PROJACTUID as PROJPLAN_UID, 
	WBS        as ACTIVITY_WBS_CODE,
	ACTDES     as ACTIVITY_NAME,
	QPRICE     as SUBMISSION_TOTAL_PRICE,
	MATERIALCOST as MATERIAL_COST,
	SOURCE_DB
from {{ source('bronze', 'PROJACTS') }}