select
    BUD_FORECAST as FORECAST_ID,
	BUD_USER     as USER_ID,
	BUD_PERIOD   as BUD_CONTROL_PERIOD_ID,
	CHAPTERNAME  as CHAPTER_NAME,
	CHAPTERDES   as CHAPTER_DES,
	SUBCHAPTERNAME as SUB_CHAPTER_NAME,
	SUBCHAPTERDES  as SUB_CHAPTER_DES,
	SUBTOPICNAME   as SUB_TOPIC_NAME,
	SUBTOPICDES    as SUB_TOPIC_DES,
	ACTBUDGETBAL   as ACTUAL_BUDGET_SPENT,
	EFORECAST      as FORECAST_TO_COMPLETE,
	EBUDGET        as CURRENT_BUDGET,
	APPROVEDTOPAY  as APPROVED_TO_PAY,
	EPREVFORECAST  as PREVIOUS_FORECAST,
    ORIGBUDGET     as ORIGINAL_BUDGET,
    DOC            as PROJECT_ID,
	SOURCE_DB
from {{ ref ('BUD_FORECAST_J') }}