select
	"PERIOD"           as BUD_CONTROL_PERIOD_ID,
	CUSTLINKING        as CUST_CUMULATIVE_INCREASE,
	EFCINCREASERECIEVE as CUST_FORECASTED_INCREASE_TO_RECIVE,
	LINKING            as CONTRACTOR_CUMULATIVE_INCREASE,
	EFCINCREASETOPAY   as CONTRACTOR_FORECASTED_INCREASE_TO_PAY,
    DOC                as PROJECT_ID,
	SOURCE_DB
from {{ ref ('BUD_FORCASTCONDITION_J') }}