--select
--    "PERIOD" as BUD_CONTROL_PERIOD_ID,
--    DOC      as PROJECT_ID,
--    DOCNO    as PROJECT_NAME,
--    CONMONTH as BUD_CONTROL_MONTH,
--    CONDATE  as BUD_CONTROL_DATE,
--    CASE
--    WHEN TRIM(CLOSED) = 'Y' THEN '1'
--    ELSE '0' END AS IS_CLOSED, --דגל האם התקציב סגור
--    CURVERSION,
--    SOURCE_DB
--from {{ ref('BUD_CONTROLPERIODS_Z_J') }}


WITH budget_periods AS (
    SELECT
        "PERIOD" AS BUD_CONTROL_PERIOD_ID,
        DOC      AS PROJECT_ID,
        DOCNO    AS PROJECT_NAME,
        CONMONTH AS BUD_CONTROL_MONTH,
        CONDATE  AS BUD_CONTROL_DATE,
        CASE
        WHEN TRIM(CLOSED) = 'Y' THEN '1'
        ELSE '0' END AS IS_CLOSED,
        CURVERSION,
        SOURCE_DB,
        MAX(CASE
            WHEN TRIM(CLOSED) = 'Y' THEN CONDATE END) OVER (PARTITION BY DOC) AS LATEST_CLOSED_DATE
    FROM {{ ref('BUD_CONTROLPERIODS_Z_J') }}
)

SELECT
    BUD_CONTROL_PERIOD_ID,
    PROJECT_ID,
    PROJECT_NAME,
    BUD_CONTROL_MONTH,
    BUD_CONTROL_DATE,
    IS_CLOSED,
    CURVERSION,
    SOURCE_DB,
    CASE
        WHEN IS_CLOSED = '1' AND BUD_CONTROL_DATE = LATEST_CLOSED_DATE 
        THEN '1' ELSE '0' END AS IS_LATEST_CLOSED_BUDGET
FROM budget_periods