select
	FORECAST       as FORECAST_ID,
    "PERIOD"       as BUD_CONTROL_PERIOD_ID,
	SUBCHAPTERNAME as SUB_CHAPTER_NAME,
	SUBCHAPTERDES  as SUB_CHAPTER_DES,
	RFORECAST      as REVENUE_FORECAST_TO_COMPLETE,
	CUSTPPC        as CUSTOMER_ACCOUNT,
	RBUDGET_NEW    as CURRENT_REVENUE_BUDGET,
	ORIGRBUDGET    as ORIGINAL_REVENUE_BUDGET,
	RPREVFORECAST  as PREVIOUS_REVENUE_FORECAST,
    DOC            as PROJECT_ID,
	SOURCE_DB
from {{ ref ('BUD_FORECAST_R_J') }}