select 
    PROJECT_NAME,
    POCKET_NUMBER,
    TARGET_CONTROL_EXPENSES,
    TARGET_CONTROL_REVENUES,
    TARGET_MANAGEMENT_EXPENSES,
    TARGET_MANAGEMENT_REVENUES
from {{ ref('CONTROL_MANAGEMENT_TARGET_STG') }}
