SELECT
    item.value:BUD_FORCASTCONDITION_SUBFORM:CUSTLINKING::FLOAT           AS CUSTLINKING,
    item.value:BUD_FORCASTCONDITION_SUBFORM:EFCINCREASERECIEVE::FLOAT    AS EFCINCREASERECIEVE,
    item.value:BUD_FORCASTCONDITION_SUBFORM:LINKING::FLOAT               AS LINKING,
    item.value:BUD_FORCASTCONDITION_SUBFORM:EFCINCREASETOPAY::FLOAT      AS EFCINCREASETOPAY,
    item.value:BUD_FORCASTCONDITION_SUBFORM:PERIOD::NUMBER(38,0)         AS PERIOD,
    item.value:BUD_FORCASTCONDITION_SUBFORM:DOC::NUMBER(38,0)            AS DOC,
    SOURCE_DB::STRING                                                    AS SOURCE_DB

FROM {{ source('json', 'BUD_FORCASTCONDITION_SUBFORM') }},
LATERAL FLATTEN(INPUT => DATA) item


