SELECT
    a.source_db AS "חברה",
    a.Control_Date AS "תאריך בקרה",
    a.Project AS "מספר פרויקט",
    a.Project_Desc AS "תאור פרויקט",
    a.Sub_Chapter AS "תת פרק",
    a.Sub_Chapter_Desc AS "תאור תת פרק",
    a.Resource AS "משאב",
    a.Resource_Desc AS "תאור משאב",
    a.Doc_Type AS "סוג תעודה",
    a.Doc_Desc AS "תאור תעודה",
    a.Supplier_No AS "מס' ספק",
    a.Supplier_Name AS "שם ספק",
    a.Doc_No AS "מספר תעודה",
    a.Exec_Month_Date AS "Date",
    a.Part_No AS "מק'ט",
    a.Part_Desc AS "תאור מוצר",
    a.Doc_Quant AS "כמות בתעודה",
    a.Factory_Unit AS "יח' מפעל",
    a.Unit_Price AS "מחיר יח'",
    a.Amount AS "סכום",
    a."הוצאות בפועל בטון",
    a."הוצאות בפועל ברזל",
    a."הוצאות בפועל ניהול שונות",
    a."הוצאות בפועל קבלנים",
    a."הוצאות בפועל ניהול אתר",
    a."הוצאות בפועל רכש",
    a."הוצאות בפועל כמות בטון",
    a."הוצאות בפועל כמות ברזל",
    a."הוצאות בפועל כמות ניהול שונות",
    a."הוצאות בפועל כמות קבלנים",
    a."הוצאות בפועל כמות ניהול אתר",
    a.Project_Expenses_Exclude_Flag,
    a.Control_Month,
    a.Entity_Name,
    p.projtypedes AS "סוג פרויקט אחרי סינון"

FROM {{ ref('PROJECT_ACTUAL_EXPENSES_STG') }} a


{{ join_valid_projects('a.Project', 'a.source_db') }}

WHERE Doc_Type<>'CO'

UNION ALL

SELECT
    SOURCE_DB AS "חברה",
    NULL AS "תאריך בקרה",
    PROJECT AS "מספר פרויקט",
    NULL AS "תאור פרויקט",
    NULL AS "תת פרק",
    NULL AS "תאור תת פרק",
    NULL AS "משאב",
    NULL AS "תאור משאב",
    EXPENSES_TYPE AS "סוג תעודה",
    EXPENSES_DESCRIPTION AS "תאור תעודה",
    NULL AS "מס' ספק",
    NULL AS "שם ספק",
    NULL AS "מספר תעודה",
    EXEC_MONTH_DATE AS "Date",
    NULL AS "מק'ט",
    NULL AS "תאור מוצר",
    NULL AS "כמות בתעודה",
    NULL AS "יח' מפעל",
    NULL AS "מחיר יח'",
    NULL AS "סכום",
    "הוצאות בפועל בטון",
    "הוצאות בפועל ברזל",
    "הוצאות בפועל ניהול שונות",
    "הוצאות בפועל קבלנים",
    "הוצאות בפועל ניהול אתר",
    "הוצאות בפועל רכש",
    "הוצאות בפועל כמות בטון",
    "הוצאות בפועל כמות ברזל",
    "הוצאות בפועל כמות ניהול שונות",
    "הוצאות בפועל כמות קבלנים",
    "הוצאות בפועל כמות ניהול אתר",
    NULL AS Project_Expenses_Exclude_Flag,
    NULL AS Control_Month,
    NULL AS Entity_Name,
    NULL AS "סוג פרויקט אחרי סינון"
FROM {{ ref('MANUAL_EXPENSES_STG') }}