SELECT
    ACCOUNT_ID,
    BALDATE,
    FNCNUM,
    ACCOUNT_DETAILS,
    ACCOUNT_DEBIT,
    DEBIT,
    ACCOUNT_CREDIT,
    CREDIT,
    SOURCE_DB,
    DATE_TEXT,
    MISSING_DATE_FLAG,
    EXECUTION_DATE,
    STORNOFLAG
FROM {{ ref('ACCFNCITEMS_STG') }}