--MED_DOCUMENTS_P
select 
	PROJECT_NAME,
	SUP_NAME,
	PARTIAL_INVOICE_NUM,
	CURDATE,
    PRICE_AFTER_DISCOUNT_INV,
    STATUS_INV,
    IS_BILLABLE,
    IS_INVOICED,
    SUP_INVOICE_NUMBER,
	SOURCE_DB
from {{ ref('CONTRACTOR_PARTIAL_INVOICES_STG') }}