--MED_PORDERS
select 
	PROJECT_NAME,
	SUP_NAME,
	SUP_DES,
	PRICETOAPP,
	MED_TYPE,
	PRICE_AFTER_DIS_CON,
	CURDATE,
    ORDER_NAME,
    MED_TYPE_DESC,
    STATUS_CON,
	SOURCE_DB 
from {{ ref('CONTRACTOR_CONTRACTS_STG') }}