select 
    PROJECT_ID,
	PROJECT_NAME,
	CONTRACTOR_NAME,
	CONTRACTOR_DES,
	PRICETOAPP,
	MED_TYPE,
	PRICE_AFTER_DIS,
	Date,
    ORDER_NAME,
    MED_TYPE_DESC,
	SOURCE_DB 
from {{ ref('CONTRACTOR_CONTRACTS_STG') }}