--MED_DOCUMENTS_P
select 
    PROJECT_ID,
	PROJECT_NAME,
	SUP_NAME,
	SUP_DES,
	PARTIAL_INVOICE_NUM,
	CURDATE,
    PRICE_AFTER_DISCOUNT_INV,
    STATUS_INV,
	SOURCE_DB
from {{ ref('CONTRACTOR_PARTIAL_INVOICES_STG') }}