--MED_PORDERITEMS_SUBFORM
SELECT
	CONTRACT_SECTION_NAME,
    CONTRACT_SECTION_DES,
    QUANTITY,
    NET_UNIT_PRICE,
    TOTAL_PRICE,
    PORD_ID,
	SOURCE_DB 
FROM {{ ref('CONTRACTOR_CONTRACTS_DETAILS_STG') }}