SELECT
    EXECUTION_DATE,
    PROJECT_DOCNO,
    ORDNAME,
    CUSTNAME,
    DISPRICE,
    MED_APPQPRICE,
    EXPECTPAY ,
    STATDES,
    BOOKNUM,
    SOURCE_DB
    
FROM {{ ref('MED_DOCUMENTS_D_STG') }}