name: Generate Snowflake RSA Key

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate key pair
        run: |
          openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out rsa_key.p8 -v2 aes256 -passout pass:${{ secrets.SNOWFLAKE_KEY_PASSPHRASE }}
          openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub -passin pass:${{ secrets.SNOWFLAKE_KEY_PASSPHRASE }}

          echo "===== PUBLIC KEY ====="
          cat rsa_key.pub

          echo "===== PRIVATE KEY ====="
          cat rsa_key.p8
