SELECT
     PROJECT_NAME,
    POCKET_NUMBER,
    TARGET_CONTROL_EXPENSES *1000 as TARGET_CONTROL_EXPENSES, 
    TARGET_CONTROL_REVENUES *1000 as  TARGET_CONTROL_REVENUES, 
    TARGET_MANAGEMENT_EXPENSES *1000 as  TARGET_MANAGEMENT_EXPENSES,
    TARGET_MANAGEMENT_REVENUES *1000 as   TARGET_MANAGEMENT_REVENUES
FROM {{ source('csv', 'CONTROL_MANAGEMENT_TARGET') }}