--ZCBS_PROJPOSITIONS_SUBFORM
select
  	DOCNO,
	DOC,
	AREA_MANAGER_POSITIONCODE,
    AREA_MANAGER_USERNAME,
    BLDUP_CONTRACT_CONTROLLER_POSITIONCODE,
    BLDUP_CONTRACT_CONTROLLER_USERNAME,
    SOURCE_DB
from {{ ref('DIM_PROJECT_ROLES_STG_Buildup') }}