select
  	DOCNO,
	DOC,
	AREA_MANAGER_POSITIONCODE,
    AREA_MANAGER_USERNAME,
    BLDUP_CONTRACT_CONTROLLER_POSITIONCODE,
    BLDUP_CONTRACT_CONTROLLER_USERNAME,
    SOURCE_DB
from {{ ref('ZCBS_PROJPOSITIONS_STG_Buildup') }}