--BUD_CONTROLPERIODS_Z
select 
    BUD_CONTROL_PERIOD_ID,
    PROJECT_ID,
    PROJECT_NAME,
    BUD_CONTROL_MONTH,
    BUD_CONTROL_DATE,
    IS_CLOSED,
    IS_LATEST_CLOSED_BUDGET,
    CURVERSION,
    SOURCE_DB
from {{ ref('PROJ_BUDGET_CONTROL_STG') }}