--BUD_FORCASTCONDITION
select
	BUD_CONTROL_PERIOD_ID,
	CUST_CUMULATIVE_INCREASE,
	CUST_FORECASTED_INCREASE_TO_RECIVE,
	CONTRACTOR_CUMULATIVE_INCREASE,
	CONTRACTOR_FORECASTED_INCREASE_TO_PAY,
    PROJECT_ID,
    CUST_CONTRACT_DEDUCTION_CALCULATED,
    CUST_CONTRACT_DEDUCTION_FUTURE,
    CONTRACTOR_CONTRACT_DEDUCTION_ACTUAL,
    CONTRACTOR_CONTRACT_DEDUCTION_FUTURE,
    CONTRACTOR_MANUAL_DEDUCTION_ACTUAL,
    CONTRACTOR_MANUAL_DEDUCTION_FUTURE,
	SOURCE_DB
from {{ ref('PROJ_BUD_FORECAST_COND_STG') }}