select 
    PROJPLAN_ID,
	PROJECT_ID,
	VERSION_ID,
	PROJPLAN_UID, 
	ACTIVITY_WBS_CODE,
	ACTIVITY_NAME,
	SUBMISSION_TOTAL_PRICE,
	MATERIAL_COST,
    SOURCE_DB
from {{ ref('PROJ_PLANNING_STG') }}