--BUD_FORCASTCONDITION
select
	BUD_CONTROL_PERIOD_ID,
	CUST_CUMULATIVE_INCREASE,
	CUST_FORECASTED_INCREASE_TO_RECIVE,
	CONTRACTOR_CUMULATIVE_INCREASE,
	CONTRACTOR_FORECASTED_INCREASE_TO_PAY,
    PROJECT_ID,
	SOURCE_DB
from {{ ref('PROJ_BUD_FORECAST_COND_STG') }}