select 
    FORECAST_ID,
	BUD_CONTROL_PERIOD_ID,
	SUB_CHAPTER_NAME,
	SUB_CHAPTER_DES,
	REVENUE_FORECAST_TO_COMPLETE,
    CUSTOMER_ACCOUNT,
	CURRENT_REVENUE_BUDGET,
	PREVIOUS_REVENUE_FORECAST,
    ORIGINAL_REVENUE_BUDGET,
	SOURCE_DB
from {{ ref('PROJ_BUD_INC_FORECAST_STG') }}