--ACCOUNTS
SELECT
	ACCOUNT     as ACCOUNT_ID,
    ACCNAME     as ACCOUNT_NUMBER,
    ACCDES      as ACCOUNT_DES,
    ACCTYPENAME as ACCOUNT_TYPE_NAME,
    BUD_DOCNO   as PROJECT_DOCNO,
    BUD_PROJ    as PROJECT_ID,
	SOURCE_DB 
FROM {{ ref('ACCOUNTS_J') }}

