--צפי חוזה קבלן
select
    SUPNAME       as SUP_NAME,
    SUBTOPICNAME  as SUB_TOPIC_NAME,
    ORIGCONTSUM   as ORIGINAL_CONTRACT_AMOUNT,
    UPDACONTSUM   as UPDATED_CONTRACT_AMOUNT,
    ACCUMSUM      as CUMULATIVE_ACCOUNT,
    PRICEINCREASE as AMOUNT_INCREASE,
    CONDATE       as BUD_CONTROL_DATE,
    DOCNO         as PROJECT_NAME,
	SOURCE_DB
from {{ ref ('BUD_CONTFORECAST_J') }}