SELECT
	DOCNO     as PROJECT_DOCNO,
    IVNUMA     as INVOICE_NAME,
    BALDATE,
    TIVNUM as RECEIPT_NAME,  
    TOTPRICE,
    RINCIPALVATCODE,
    RINCIPALVATDES,
    PEREXTRACTION,
    TOTPRICEIV,
    TOTKEREN,
    IVDATE as INVOICE_DATE,
	SOURCE_DB 
FROM {{ ref('ZCBS_PAYMENTRECEIPT_J') }}

