SELECT
	DOCNO   as PROJECT_NAME,
    IVNUMA  as INVOICE_NUM,
    IVDATE  as INVOICE_DATE,
    BALDATE,
    IVNUM  as RECEIPT_NUM,  
    RINCIPALVATCODE,
    RINCIPALVATDES,
    PEREXTRACTION,
    PRICEINOUT, --סכום התקבול/תשלום
    TOTKEREN, --סכום הקרן
    TOTMAAM, --סכום המעמ
    CASHFLOWCLASSIFDES AS CLASSIFICATION, --תקבול/תשלום
    ACCNAME,
    ACCDES,
    TIVDATE,
    FNCDATE,
	SOURCE_DB 
FROM {{ ref('ZCBS_PAYMENTRECEIPT_J') }}