--MED_DOCUMENTS_P
SELECT
	PROJDOCNO as PROJECT_NAME,
	SUPNAME   as SUP_NAME,
	BOOKNUM   as PARTIAL_INVOICE_NUM,
	CURDATE,
    DISPRICE  as PRICE_AFTER_DISCOUNT_INV,
    STATDES   as STATUS_INV,
    FLAG      as IS_BILLABLE,
    IVALL     as IS_INVOICED,
    ZCBS_IVNUM as SUP_INVOICE_NUMBER,
	SOURCE_DB
FROM {{ ref('MED_DOCUMENTS_P_J') }}
WHERE STATDES NOT IN ('מבוטלת', 'טיוטא')