SELECT
    DOCPROJ   as PROJECT_ID,
	PROJDOCNO as PROJECT_NAME,
	SUPNAME   as CONTRACTOR_NAME,
	CDES      as CONTRACTOR_DES,
	ZCBS_PRICETOAPP as PRICETOAPP,
	MED_TYPE        as MED_TYPE,
	DISPRICE        as PRICE_AFTER_DIS,
	CURDATE         as DATE,
    ORDNAME         as ORDER_NAME,
	SOURCE_DB 
FROM {{ source('bronze', 'MED_PORDERS') }}