SELECT
    DOCPROJ   as PROJECT_ID,
	PROJDOCNO as PROJECT_NAME,
	SUPNAME   as CONTRACTOR_NAME,
	CDES      as CONTRACTOR_DES,
	ZCBS_PRICETOAPP as PRICETOAPP,
	MED_TYPE        as MED_TYPE,
	DISPRICE        as PRICE_AFTER_DIS_CON,
	CURDATE,
    ORDNAME         as ORDER_NAME,
    CASE WHEN MED_TYPE = 'CO' THEN 'חוזה'
         WHEN MED_TYPE = 'CH' THEN 'הוראת שינוי'
    ELSE MED_TYPE END as MED_TYPE_DESC,
    STATDES         as STATUS_CON,
	SOURCE_DB 
FROM {{ ref('MED_PORDERS') }}