--MED_DOCUMENTS_P
SELECT
<<<<<<< HEAD
   
=======
>>>>>>> 498ef3077a0f51310777349d128e35c8a0d7c7a3
	PROJDOCNO as PROJECT_NAME,
	SUPNAME   as SUP_NAME,
	BOOKNUM   as PARTIAL_INVOICE_NUM,
	CURDATE,
    DISPRICE  as PRICE_AFTER_DISCOUNT_INV,
    STATDES   as STATUS_INV,
	SOURCE_DB
FROM {{ ref('MED_DOCUMENTS_P_J') }}

