--MED_PORDERITEMS_SUBFORM
SELECT
	MED_SECTION as CONTRACT_SECTION_NAME,
    MED_SECDES  as CONTRACT_SECTION_DES,
    TQUANT      as QUANTITY,
    PRICE       as NET_UNIT_PRICE,
    QPRICE      as TOTAL_PRICE,
    ORD         as PORD_ID,
	SOURCE_DB 
FROM {{ ref('MED_PORDERITEMS_J') }}