--MEDR_GUARANTCHNGLOG_SUBFORM
select
    CHNGTYPE  as CHANGE_TYPE,
    PREVVALUE as PREV_VALUE,
    NEWVALUE  as NEW_VALUE,
    STATDES   as STAT_IN_CHANGE,
    UDATE     as CHANGE_DATE,
    DOCNO     as GUARANTEE_NAME, --מספר ערבות
    SOURCE_DB
from {{ ref('MEDR_GUARANTCHNGLOG_J') }}