--MEDR_GUARANTEES
select
    PROJNO   as PROJECT_NAME,
    PROJDES  as PROJECT_DES,
    BANKNAME as BANK_NAME,
    GUARANTYPEDES as GUARANTEE_TYPE_DES,
    BANKREF       as BANK_GUARANTEE_REFERENCE,
    ACCDES        as ACC_DES,
    GSUM          as GUARANTEE_AMOUNT,
    EXCHSUM       as REVALUED_GUARANTEE_AMOUNT,
    SDATE         as GUARANTEE_START_DATE,
    EXPDATE       as GUARANTEE_END_DATE,
    SOURCE_DB
from {{ ref('MEDR_GUARANTEES_J') }}