SELECT
    a.DOC_PROJECT,
    IVDATE ::DATE AS  INVOICE_DATE,
    INVOICES_ACTUALLY_NEW,
    INVOICES_ACTUALLY_EXPENSE_NEW,
    a.SOURCE_DB
FROM {{ ref('INVOICES_ACTUALLY_J') }} a

{{ join_valid_projects('a.DOC_PROJECT', 'a.SOURCE_DB') }}

