SELECT
    IVNUM AS INVOICE_NUMBER,
    DOC_PROJECT,
    IVDATE ::DATE AS  INVOICE_DATE,
    (TOTPRICE/1000)::INTEGER AS TOTAL_PRICE,
    IV AS id,
    SOURCE_DB
FROM {{ source('bronze', 'INVOICES') }}
