SELECT
    DATABASE as source_db,
    PROJECT_NUMBER as Project,
    TRY_TO_DATE(EXPENSES_DATE) AS Exec_Month_Date,
    EXPENSES_DESCRIPTION,
    EXPENSES_LINE_CODE,
    EXPENSES_TYPE,
    EXPENSES_AMOUNT,
    EXPENSES_QTY

FROM {{ source('csv', 'MANUAL_EXPENSES') }}