--MED_ORDERS_J
select
    DOCNO      as PROJECT_NAME,
    PROJ       as PROJECT_ID,
    CUSTNAME   as CUST_NAME,
    MED_PAYDES as MED_PAY_DES,
    MED_TYPE   as MED_TYPE,
    TOTPRICE   as TOTAL_PRICE,
    TOTPRICE / 1000 as TOTAL_PRICE_K,
    CURDATE,
    ORDSTATUSDES as ORD_STATUS_DES,
    SOURCE_DB
from {{ ref('MED_ORDERS_J') }}