select
    SECTION   as SECTION_NUMBER,
    SECDES    as SECTION_DES,
    QPRICE_TO as CUM_AMOUNT_AFTER_DISCOUNT,
    QPRICE_TO_BD as CUM_AMOUNT_BEFORE_DISCOUNT,
    DOC       as PROJECT_ID,
    PROJDOCNO as PROJECT_NAME,
    TRY_TO_DATE('01/' || MED_EXEMONTH, 'DD/MM/YY') as EXECUTION_DATE,
	SOURCE_DB
from {{ ref ('MED_APPTRANS_SUBFORM_J') }}