select
    BUD_FORECAST as FORECAST_ID,
	BUD_USER     as USER_ID,
	BUD_PERIOD   as BUD_CONTROL_PERIOD_ID,
	CHAPTERNAME  as CHAPTER_NAME,
	CHAPTERDES   as CHAPTER_DES,
	SUBCHAPTERNAME as SUB_CHAPTER_NAME,
	SUBCHAPTERDES  as SUB_CHAPTER_DES,
	SUBTOPICNAME   as SUB_TOPIC_NAME,
	SUBTOPICDES    as SUB_TOPIC_DES,
	ACTBUDGETBAL      as ACTUAL_BUDGET_SPENT,
    ACTBUDGETBAL/1000 as ACTUAL_BUDGET_SPENT_K, --באלפי ש"ח
	EFORECAST      as FORECAST_TO_COMPLETE,
    EFORECAST/1000 as FORECAST_TO_COMPLETE_K, --באלפי ש"ח
	EBUDGET        as CURRENT_BUDGET,
    EBUDGET/1000   as CURRENT_BUDGET_K, --באלפי ש"ח
	APPROVEDTOPAY      as APPROVED_TO_PAY,
    APPROVEDTOPAY/1000 as APPROVED_TO_PAY_K, --באלפי ש"ח
	EPREVFORECAST      as PREVIOUS_FORECAST,
    EPREVFORECAST/1000 as PREVIOUS_FORECAST_K, --באלפי ש"ח
    ORIGBUDGET      as ORIGINAL_BUDGET,
    ORIGBUDGET/1000 as ORIGINAL_BUDGET_K, --באלפי ש"ח
    DOC            as PROJECT_ID,
    CONDATE        as BUD_CONTROL_DATE,
    TOPICNAME      as TOPIC_NAME,
    TOPICDES       as TOPIC_DES,
	SOURCE_DB
from {{ ref ('BUD_FORECAST_J') }}