select
    PROJACT    as PROJPLAN_ID,
	DOC        as PROJECT_ID,
	"VERSION"  as VERSION_ID,
	PROJACTUID as PROJPLAN_UID, 
	WBS        as ACTIVITY_WBS_CODE,
	ACTDES     as ACTIVITY_NAME,
	QPRICE     as SUBMISSION_TOTAL_PRICE,
	MATERIALCOST as MATERIAL_COST,
    BUD_SUBCHAPTERNAME as BUD_SUBCHAPTER_NAME,
    BUD_SUBCHAPTERDES  as BUD_SUBCHAPTER_DES,
    DOCNO              as PROJECT_NAME,
    BIDS_ENTRY2        as CHAPTER_NAME,
    PRICE              as PRICE_PER_UNIT,
    MED_PROJACTCOST    as COST_PER_UNIT, 
	SOURCE_DB
from {{ ref ('PROJACTS_J_new') }}