select
	FORECAST       as FORECAST_ID,
    "PERIOD"       as BUD_CONTROL_PERIOD_ID,
	SUBCHAPTERNAME as SUB_CHAPTER_NAME,
	SUBCHAPTERDES  as SUB_CHAPTER_DES,
	RFORECAST      as REVENUE_FORECAST_TO_COMPLETE,
    RFORECAST/1000 as REVENUE_FORECAST_TO_COMPLETE_K, --באלפי ש"ח
	CUSTPPC        as CUSTOMER_ACCOUNT,
    CUSTPPC/1000   as CUSTOMER_ACCOUNT_K, --באלפי ש"ח
	RBUDGET_NEW    as CURRENT_REVENUE_BUDGET,
    RBUDGET_NEW/1000    as CURRENT_REVENUE_BUDGET_K, --באלפי ש"ח
	ORIGRBUDGET         as ORIGINAL_REVENUE_BUDGET,
    ORIGRBUDGET/1000    as ORIGINAL_REVENUE_BUDGET_K, --באלפי ש"ח
	RPREVFORECAST       as PREVIOUS_REVENUE_FORECAST,
    RPREVFORECAST/1000  as PREVIOUS_REVENUE_FORECAST_K, --באלפי ש"ח
    DOC            as PROJECT_ID,
    CONDATE        as BUD_CONTROL_DATE,
	SOURCE_DB
from {{ ref ('BUD_FORECAST_R_J') }}