select
	"PERIOD"           as BUD_CONTROL_PERIOD_ID,
	CUSTLINKING        as CUST_CUMULATIVE_INCREASE,
	EFCINCREASERECIEVE as CUST_FORECASTED_INCREASE_TO_RECIVE,
	LINKING            as CONTRACTOR_CUMULATIVE_INCREASE,
	EFCINCREASETOPAY   as CONTRACTOR_FORECASTED_INCREASE_TO_PAY,
    DOC                as PROJECT_ID,
    APPCONTREDUCTIONS  as CUST_CONTRACT_DEDUCTION_CALCULATED,
    BSA_CONTDEDUCTION1 as CUST_CONTRACT_DEDUCTION_FUTURE,
    APPMANREDUCTIONS   as CONTRACTOR_CONTRACT_DEDUCTION_ACTUAL,
    EFCMANREDUCTION    as CONTRACTOR_CONTRACT_DEDUCTION_FUTURE,
    CPPCCONTDEDUCTION  as CONTRACTOR_MANUAL_DEDUCTION_ACTUAL,
    BSA_CONTDEDUCTION  as CONTRACTOR_MANUAL_DEDUCTION_FUTURE,
	SOURCE_DB
from {{ ref ('BUD_FORCASTCONDITION_J') }}