--PORDERS
SELECT
    PROJDOCNO as PROJECT_NAME,
	SUPNAME   as SUP_NAME,
	CURDATE,
	DISPRICE  as PRICE_AFTER_DIS_PORD,
	STATDES   as STATUS_PORD,
    ORDNAME   as PORDER_NAME,
	SOURCE_DB
FROM {{ ref('PORDERS_J') }}