--PORDERS
SELECT
    PROJDOCNO as PROJECT_NAME,
	SUPNAME   as SUP_NAME,
	CURDATE,
	DISPRICE  as PRICE_AFTER_DIS_PORD,
	STATDES   as STATUS_PORD ,
	SOURCE_DB
FROM {{ source('bronze', 'PORDERS') }}