--33 מנהל איזור
--11 מנהל פרויקט
select
    DOCNO as PROJECT_NAME,
	DOC   as PROJECT_ID,
	POSITIONCODE as POSITION_CODE,
	POSITIONDES  as POSITION_DES,
    USERNAME     as USER_NAME,
    case when POSITIONCODE = 33 then POSITIONCODE end as AREA_MANAGER_POSITIONCODE,
    case when POSITIONCODE = 33 then USERNAME end     as AREA_MANAGER_USERNAME,
    case when POSITIONCODE = 11 then POSITIONCODE end as PROJECT_MANAGER_POSITIONCODE,
    case when POSITIONCODE = 11 then USERNAME end     as PROJECT_MANAGER_USERNAME,
    SOURCE_DB
from {{ ref ('ZCBS_PROJPOSITIONS_J') }}
