SELECT
    sub.value:CUSTLINKING::FLOAT           AS CUSTLINKING,
    sub.value:EFCINCREASERECIEVE::FLOAT    AS EFCINCREASERECIEVE,
    sub.value:LINKING::FLOAT               AS LINKING,
    sub.value:EFCINCREASETOPAY::FLOAT      AS EFCINCREASETOPAY,
    sub.value:PERIOD::NUMBER(38,0)         AS PERIOD,
    sub.value:DOC::NUMBER(38,0)            AS DOC,
    sub.value:APPCONTREDUCTIONS::FLOAT     AS APPCONTREDUCTIONS,
    sub.value:BSA_CONTDEDUCTION1::FLOAT    AS BSA_CONTDEDUCTION1,
    sub.value:APPMANREDUCTIONS::FLOAT      AS APPMANREDUCTIONS,
    sub.value:EFCMANREDUCTION::FLOAT       AS EFCMANREDUCTION,
    sub.value:CPPCCONTDEDUCTION::FLOAT     AS CPPCCONTDEDUCTION,
    sub.value:BSA_CONTDEDUCTION::FLOAT     AS BSA_CONTDEDUCTION,
    item.value:DOCNO::VARCHAR              AS DOCNO, --שדה של האבא
    SOURCE_DB::STRING                      AS SOURCE_DB

FROM {{ source('json', 'BUD_FORCASTCONDITION_SUBFORM') }},
LATERAL FLATTEN(input => DATA) item,
LATERAL FLATTEN(input => item.value:BUD_FORCASTCONDITION_SUBFORM) sub