SELECT
    item.value:BUD_FORCASTCONDITION_SUBFORM:CUSTLINKING::FLOAT           AS CUSTLINKING,
    item.value:BUD_FORCASTCONDITION_SUBFORM:EFCINCREASERECIEVE::FLOAT    AS EFCINCREASERECIEVE,
    item.value:BUD_FORCASTCONDITION_SUBFORM:LINKING::FLOAT               AS LINKING,
    item.value:BUD_FORCASTCONDITION_SUBFORM:EFCINCREASETOPAY::FLOAT      AS EFCINCREASETOPAY,
    item.value:BUD_FORCASTCONDITION_SUBFORM:PERIOD::NUMBER(38,0)         AS PERIOD,
    item.value:BUD_FORCASTCONDITION_SUBFORM:DOC::NUMBER(38,0)            AS DOC,
    item.value:BUD_FORCASTCONDITION_SUBFORM:APPCONTREDUCTIONS::FLOAT     AS APPCONTREDUCTIONS,
    item.value:BUD_FORCASTCONDITION_SUBFORM:BSA_CONTDEDUCTION1::FLOAT    AS BSA_CONTDEDUCTION1,
    item.value:BUD_FORCASTCONDITION_SUBFORM:APPMANREDUCTIONS::FLOAT      AS APPMANREDUCTIONS,
    item.value:BUD_FORCASTCONDITION_SUBFORM:EFCMANREDUCTION::FLOAT       AS EFCMANREDUCTION,
    item.value:BUD_FORCASTCONDITION_SUBFORM:CPPCCONTDEDUCTION::FLOAT     AS CPPCCONTDEDUCTION,
    item.value:BUD_FORCASTCONDITION_SUBFORM:BSA_CONTDEDUCTION::FLOAT     AS BSA_CONTDEDUCTION,
    SOURCE_DB::STRING                                                    AS SOURCE_DB

FROM {{ source('json', 'BUD_FORCASTCONDITION_SUBFORM') }},
LATERAL FLATTEN(INPUT => DATA) item


