--MEDR_GUARANTCHNGLOG_SUBFORM
SELECT
    sub.value:CHNGTYPE::STRING  AS CHNGTYPE,
    sub.value:PREVVALUE::STRING AS PREVVALUE,
    sub.value:NEWVALUE::STRING  AS NEWVALUE,
    sub.value:STATDES::STRING   AS STATDES,
    sub.value:UDATE::DATE       AS UDATE,
    item.value:DOCNO::VARCHAR   AS DOCNO, --שדה של האבא
    SOURCE_DB::STRING           AS SOURCE_DB

FROM {{ source('json', 'MEDR_GUARANTCHNGLOG_SUBFORM') }},
LATERAL FLATTEN(INPUT => DATA) item,
LATERAL FLATTEN(INPUT => item.value:MEDR_GUARANTCHNGLOG_SUBFORM) sub