SELECT
    item.value:FOREX::NUMBER(13,0)                    AS FOREX,
    item.value:PROJDOCNO::string                      AS PROJDOCNO,
    item.value:BST_FOREXSUBA_SUBFORM:MANAGE1::FLOAT   AS MANAGE1,
    item.value:BST_FOREXSUBA_SUBFORM:MATERIAL1::FLOAT AS MATERIAL1,
    item.value:BST_FOREXSUBA_SUBFORM:MATERIAL2::FLOAT AS MATERIAL2,
    item.value:BST_FOREXSUBA_SUBFORM:MANAGE6::FLOAT   AS MANAGE6,
    item.value:BST_FOREXSUBA_SUBFORM:MATERIAL4::FLOAT AS MATERIAL4,
    item.value:BST_FOREXSUBA_SUBFORM:MANAGE3::FLOAT   AS MANAGE3,
    item.value:BST_FOREXSUBA_SUBFORM:MANAGE7::FLOAT   AS MANAGE7,
    item.value:BST_FOREXSUBA_SUBFORM:MANAGE8::FLOAT   AS MANAGE8,
    SOURCE_DB::STRING AS SOURCE_DB

FROM {{ source('json', 'BST_FOREXSUBA_SUBFORM') }},
LATERAL FLATTEN(input => DATA) item