SELECT
    IVNUM AS INVOICE_NUMBER,
    DOC_PROJECT,
    TO_CHAR(TO_DATE(INVOICES.IVDATE), 'DD/MM/YYYY') AS INVOICE_DATE,
    TOTPRICE::FLOAT AS TOTAL_PRICE,
    IV AS id
FROM {{ source('bronze', 'INVOICES') }}
